-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_electoral_district_job`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_electoral_district_job
-- *
-- * Pre-defined district districting jobs
-- *
-- *******************************************************/
CREATE TABLE `civicrm_electoral_district_job` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique DistrctJob ID',
  `description` varchar(512) COMMENT 'Description of the district job ',
  `contact_ids` text COMMENT 'Serialized list of contact ids to re-district',
  `status` varchar(10) COMMENT 'Status of the job',
  `status_message` varchar(512) COMMENT 'Status explanation of the job',
  `offset` int unsigned DEFAULT 0 COMMENT 'Keeps track of the index of the last contact id processed',
  `date_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When was the job created.',
  `date_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When was the job last updated.',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
